name: 'snowflake_dbt_telephony_insights'
version: '1.0.0'
profile: 'snowflake_dbt_telephony_insights_raw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_dbt_telephony_insights:
    staging:
      +materialized: view
      +snowflake_warehouse: tel_insights_etl
    # Configuration pour le dossier 'marts'
    marts:
      +materialized: table # Les modèles marts seront des tables
      +schema: MARTS       # Résultat: ANALYTICS_DEV.MARTS.fct_communications
