name: 'telephony_insights'
version: '1.0.0'
config-version: 2

profile: 'snowflake_dbt_telephony_insights_raw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# CONFIGURATION DES SCHÉMAS CIBLES
models:
  telephony_insights:
    # Configuration pour la couche STAGING
    staging:
      +database: STAGING        # Force l'écriture dans la DB STAGING
      +schema: DBT_STAGING      # Force le schéma
      +materialized: view       # Les stagings sont souvent des vues (plus rapide)

    # Configuration pour la couche MARTS
    marts:
      +database: MARTS          # Force l'écriture dans la DB MARTS
      +schema: PROD             # Force le schéma
      +materialized: table      # Les tables finales sont des tables (pour la perf Streamlit)