-- À exécuter en tant que ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- 1. Création des Rôles
CREATE ROLE IF NOT EXISTS STREAMLIT_ROLE COMMENT = 'Rôle pour l application Streamlit';
CREATE ROLE IF NOT EXISTS DBT_ROLE COMMENT = 'Rôle pour les transformations dbt';
CREATE ROLE IF NOT EXISTS AIRFLOW_ROLE COMMENT = 'Rôle pour l orchestration Airflow';

-- 2. Création des Utilisateurs (Exemple)
-- (Gérez les mots de passe de manière sécurisée, idéalement via des clés/secrets)
CREATE USER IF NOT EXISTS STREAMLIT_APP_USER
    -- [SÉCURITÉ] Utilisation de la clé publique
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4Pdih1fHCPhIvw6BAj9d
Ini/l037a7yP0B0iXXws9L7d0OK3ce0JLGrF3JPyd4/WTkjco1AqURbVGTCiOuO6
3iAWvJs+eo22Qj2O9M5wTrqMcYxnBOQ1P2yzlr/ghsQFSxedZKN6t44XxlHbpjq2
2wPad3QSxJ2M0QDtDgWztSzZY4V0qsn0mhtQ7KMIzwUSO8pXc3htARFhd5Dee/9b
zmdO3uG2p4cpt8XXXj2ukstKtMSAJNL9R8CzyhbAUkbpnLa9cpVRRcxnp77gM1ku
GG9K7XaKaHSKFCXqz1qrDpUbSyI5QFwBNI5o238XnwPXRrPfPgCPXg06KXP2W5tc
XQIDAQAB'
    DEFAULT_ROLE = STREAMLIT_ROLE
    DEFAULT_WAREHOUSE = STREAMLIT_WH
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_NAMESPACE = AUTH_DB.PROD
    COMMENT = 'Utilisateur de service (Clé-Paire) pour la connexion Streamlit';

CREATE USER IF NOT EXISTS DBT_USER
    PASSWORD = 'VOTRE_MOT_DE_PASSE_SECRET'
    LOGIN_NAME = 'DBT_USER'
    DEFAULT_ROLE = DBT_ROLE
    DEFAULT_WAREHOUSE = DBT_WH;

-- 3. Attribution des Rôles aux Utilisateurs
GRANT ROLE STREAMLIT_ROLE TO USER STREAMLIT_APP_USER;
GRANT ROLE DBT_ROLE TO USER DBT_USER;
GRANT ROLE DBT_ROLE TO ROLE AIRFLOW_ROLE;

-- 4. Attribution des Rôles au SYSADMIN (pour la gestion)
GRANT ROLE STREAMLIT_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_ROLE TO ROLE SYSADMIN;

-- À exécuter en tant que SYSADMIN
USE ROLE SYSADMIN;

-- 5. Création des Warehouses
CREATE WAREHOUSE IF NOT EXISTS STREAMLIT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Entrepôt dédié à l''application Streamlit PROJET TELEPHONY INSIGHTS';;

CREATE WAREHOUSE IF NOT EXISTS DBT_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Entrepôt dédié aux transformations dbt pour PROJET TELEPHONY INSIGHTS';

-- 6. Création des Bases de Données
CREATE DATABASE IF NOT EXISTS AUTH_DB
COMMENT = 'Base de données pour l''authentification des utilisateurs de l''application Streamlit';
CREATE DATABASE IF NOT EXISTS DOSSIERS_DB
COMMENT = 'Base de données pour les procédures';
CREATE DATABASE IF NOT EXISTS RAW_DATA
COMMENT = 'zone d atterrissage (landing zone) des fichiers CSV (MT20, MT24...) uploadés par Streamlit';
CREATE DATABASE IF NOT EXISTS STAGING
COMMENT = 'Zone de travail exclusive pour dbt. C est ici que dbt nettoie, standardise et unifie les données brutes.';
CREATE DATABASE IF NOT EXISTS MARTS
COMMENT = 'Base de données des datamarts finaux pour les analyses et visualisations.';

-- 7. Création des Schémas et Tables
USE DATABASE AUTH_DB;
CREATE SCHEMA IF NOT EXISTS PROD;
CREATE TABLE IF NOT EXISTS AUTH_DB.PROD.USERS (
    EMAIL VARCHAR PRIMARY KEY,
    PASSWORD_HASH VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE DATABASE DOSSIERS_DB;
CREATE SCHEMA IF NOT EXISTS PROD;
CREATE TABLE IF NOT EXISTS DOSSIERS_DB.PROD.DOSSIERS (
    DOSSIER_ID VARCHAR PRIMARY KEY,
    PV_NUMBER VARCHAR NOT NULL,
    NOM_DOSSIER VARCHAR,
    TYPE_ENQUETE VARCHAR,
    DIRECTEUR_ENQUETE VARCHAR,
    DATE_SAISINE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY_USER_EMAIL VARCHAR -- REFERENCES AUTH_DB.PROD.USERS(EMAIL)
);

USE DATABASE RAW_DATA;
CREATE SCHEMA IF NOT EXISTS PNIJ_SRC;
-- Créer les tables RAW (ex: RAW_MT20) avec TOUTES les colonnes en VARCHAR
-- plus les colonnes de métadonnées
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_MT20 (
    DOSSIER_ID VARCHAR,
    SOURCE_FILENAME VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    -- ... toutes les colonnes de vos CSV (TYPE, DATE, CIBLE, etc.) en VARCHAR
    "TYPE"                  VARCHAR,
    "DATE"                  VARCHAR,
    "CIBLE"                 VARCHAR,
    "CORRESPONDANT"         VARCHAR,
    "TYPE CORRESPONDANT"    VARCHAR,
    "DIRECTION"             VARCHAR,
    "DUREE"                 VARCHAR,
    "COMP."                 VARCHAR,
    "EFFICACITE"            VARCHAR,
    "IMSI"                  VARCHAR,
    "IMEI"                  VARCHAR,
    "CELLID"                VARCHAR,
    "ADRESSE IP VO WIFI"    VARCHAR,
    "PORT SOURCE VO WIFI"   VARCHAR,
    "ADRESSE2"              VARCHAR,
    "ADRESSE3"              VARCHAR,
    "ADRESSE4"              VARCHAR,
    "ADRESSE5"              VARCHAR,
    "CODE POSTAL"           VARCHAR,
    "VILLE"                 VARCHAR,
    "PAYS"                  VARCHAR,
    "TYPE-COORD"            VARCHAR,
    "X"                     FLOAT,
    "Y"                     FLOAT
);
-- (Faire de même pour RAW_MT24, RAW_HREF_ZONE)
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_MT24 (
    DOSSIER_ID VARCHAR,
    SOURCE_FILENAME VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    -- ... toutes les colonnes de vos CSV (TYPE, DATE, CIBLE, etc.) en VARCHAR
    "TYPE"                  VARCHAR,
    "DATE"                  VARCHAR,
    "CIBLE"                 VARCHAR,
    "CORRESPONDANT"         VARCHAR,
    "TYPE CORRESPONDANT"    VARCHAR,
    "DIRECTION"             VARCHAR,
    "DUREE"                 VARCHAR,
    "COMP."                 VARCHAR,
    "EFFICACITE"            VARCHAR,
    "IMSI"                  VARCHAR,
    "IMEI"                  VARCHAR,
    "CELLID"                VARCHAR,
    "ADRESSE IP VO WIFI"    VARCHAR,
    "PORT SOURCE VO WIFI"   VARCHAR,
    "ADRESSE2"              VARCHAR,
    "ADRESSE3"              VARCHAR,
    "ADRESSE4"              VARCHAR,
    "ADRESSE5"              VARCHAR,
    "CODE POSTAL"           VARCHAR,
    "VILLE"                 VARCHAR,
    "PAYS"                  VARCHAR,
    "TYPE-COORD"            VARCHAR,
    "X"                     FLOAT,
    "Y"                     FLOAT
);

USE DATABASE MARTS;
CREATE SCHEMA IF NOT EXISTS PROD;

USE DATABASE STAGING;

CREATE SCHEMA IF NOT EXISTS DBT_STAGING;
-- 8. Attribution des Privilèges (LE PLUS IMPORTANT)

-- 8.1. Privilèges pour STREAMLIT_ROLE
-- WH
GRANT USAGE ON WAREHOUSE STREAMLIT_WH TO ROLE STREAMLIT_ROLE;
-- AUTH_DB
GRANT USAGE ON DATABASE AUTH_DB TO ROLE STREAMLIT_ROLE;

GRANT USAGE ON DATABASE AUTH_DB TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA AUTH_DB.PROD TO ROLE STREAMLIT_ROLE;
GRANT SELECT, INSERT ON TABLE AUTH_DB.PROD.USERS TO ROLE STREAMLIT_ROLE;
-- DOSSIERS_DB
GRANT USAGE ON DATABASE DOSSIERS_DB TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA DOSSIERS_DB.PROD TO ROLE STREAMLIT_ROLE;
GRANT SELECT, INSERT ON TABLE DOSSIERS_DB.PROD.DOSSIERS TO ROLE STREAMLIT_ROLE;
-- RAW_DATA (Insertions uniquement)
GRANT USAGE ON DATABASE RAW_DATA TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA RAW_DATA.PNIJ_SRC TO ROLE STREAMLIT_ROLE;
GRANT INSERT ON TABLE RAW_DATA.PNIJ_SRC.RAW_MT20 TO ROLE STREAMLIT_ROLE;
GRANT INSERT ON TABLE RAW_DATA.PNIJ_SRC.RAW_MT24 TO ROLE STREAMLIT_ROLE;

-- MARTS (Lectures uniquement)
GRANT USAGE ON DATABASE MARTS TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA MARTS.PROD TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS.PROD TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MARTS.PROD TO ROLE STREAMLIT_ROLE;

-- 8.2. Privilèges pour DBT_ROLE
-- WH
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
-- RAW_DATA (Lectures uniquement)
GRANT USAGE ON DATABASE RAW_DATA TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA RAW_DATA.PNIJ_SRC TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DATA.PNIJ_SRC TO ROLE DBT_ROLE;
-- STAGING (Contrôle total)
GRANT USAGE ON DATABASE STAGING TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA, USAGE ON DATABASE STAGING TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STAGING.DBT_STAGING TO ROLE DBT_ROLE; -- Simplifié, dbt gère son schéma
-- MARTS (Contrôle total pour créer modèles/vues)
GRANT USAGE ON DATABASE MARTS TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA, USAGE ON DATABASE MARTS TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA MARTS.PROD TO ROLE DBT_ROLE; -- Simplifié