# models/staging/sources.yml

version: 2

sources:
  - name: raw
    # Définit la connexion à votre couche RAW
    database: raw
    schema: csv

    tables:
      # --- Fichiers de réquisition ---

      - name: src_mt20_orange_csv
        description: "Données brutes MT20 (ligne) Orange."

      - name: src_mt20_sfr_csv
        description: "Données brutes MT20 (ligne) SFR."

      - name: src_mt24_orange_csv
        description: "Données brutes MT24 (boîtier) Orange."

      - name: src_mt24_sfr_csv
        description: "Données brutes MT24 (boîtier) SFR."