-- ===========================================================================
-- 0. INITIALISATION DE L'ENVIRONNEMENT (RESET SI BESOIN)
-- ===========================================================================
USE ROLE ACCOUNTADMIN;

-- Création de la base d'outils transverses (Nouveau !)
CREATE DATABASE IF NOT EXISTS UTILS_DB COMMENT = 'Fonctions et procédures transverses (UDF)';
CREATE SCHEMA IF NOT EXISTS UTILS_DB.PUBLIC;

-- ===========================================================================
-- 1. GESTION DES RÔLES ET UTILISATEURS
-- ===========================================================================
CREATE ROLE IF NOT EXISTS STREAMLIT_ROLE COMMENT = 'Rôle applicatif Streamlit';
CREATE ROLE IF NOT EXISTS DBT_ROLE       COMMENT = 'Rôle de transformation dbt';
CREATE ROLE IF NOT EXISTS AIRFLOW_ROLE   COMMENT = 'Rôle d''orchestration';

-- Utilisateurs (Exemples)
CREATE USER IF NOT EXISTS STREAMLIT_APP_USER
    PASSWORD = 'StrongPassword123!' -- À changer
    DEFAULT_ROLE = STREAMLIT_ROLE
    DEFAULT_WAREHOUSE = STREAMLIT_WH;

CREATE USER IF NOT EXISTS DBT_USER
    PASSWORD = 'StrongPassword123!' -- À changer
    DEFAULT_ROLE = DBT_ROLE
    DEFAULT_WAREHOUSE = DBT_WH;

-- Hiérarchie
GRANT ROLE STREAMLIT_ROLE TO USER STREAMLIT_APP_USER;
GRANT ROLE DBT_ROLE TO USER DBT_USER;
GRANT ROLE DBT_ROLE TO ROLE AIRFLOW_ROLE;
GRANT ROLE STREAMLIT_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_ROLE TO ROLE SYSADMIN;

-- ===========================================================================
-- 2. GESTION DU COMPUTE (WAREHOUSES)
-- ===========================================================================
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS STREAMLIT_WH
    WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DBT_WH
    WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

-- ===========================================================================
-- 3. ARCHITECTURE DES DONNÉES (BASES & TABLES)
-- ===========================================================================

-- --- A. Bases de Données ---
CREATE DATABASE IF NOT EXISTS AUTH_DB;
CREATE SCHEMA IF NOT EXISTS AUTH_DB.PROD;
CREATE DATABASE IF NOT EXISTS DOSSIERS_DB;
CREATE SCHEMA IF NOT EXISTS DOSSIERS_DB.PROD;
CREATE DATABASE IF NOT EXISTS RAW_DATA;
CREATE SCHEMA IF NOT EXISTS RAW_DATA.PNIJ_SRC;

-- --- B. Bases de Transformation (Mise à jour architecture dbt) ---
-- On utilise une base unique 'TRANSFORM_DB' ou on garde votre structure éclatée.
-- Pour coller à votre structure existante :
CREATE DATABASE IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS STAGING.DBT_STAGING;

-- >>> NOUVEAU : Schéma INTERMEDIATE <<<
-- On peut le mettre dans STAGING ou dans une base dédiée.
-- Ici je le mets dans la base STAGING pour simplifier.
CREATE SCHEMA IF NOT EXISTS STAGING.INTERMEDIATE;

CREATE DATABASE IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS MARTS.PROD;


-- --- C. Création des Tables (Structure inchangée) ---
-- AUTH
CREATE TABLE IF NOT EXISTS AUTH_DB.PROD.USERS (
    EMAIL VARCHAR PRIMARY KEY, NOM_PRENOM VARCHAR, SERVICE VARCHAR, PASSWORD_HASH VARCHAR, CREATED_AT TIMESTAMP_NTZ
);

-- DOSSIERS
CREATE TABLE IF NOT EXISTS DOSSIERS_DB.PROD.DOSSIERS (
    DOSSIER_ID VARCHAR PRIMARY KEY, STATUS VARCHAR, PV_NUMBER VARCHAR, NOM_DOSSIER VARCHAR,
    TYPE_ENQUETE VARCHAR, DIRECTEUR_ENQUETE VARCHAR, DATE_SAISINE DATE,
    CREATED_AT TIMESTAMP_NTZ, CREATED_BY_USER_EMAIL VARCHAR
);
CREATE TABLE IF NOT EXISTS DOSSIERS_DB.PROD.FILES_LOG (
    FILE_ID VARCHAR(36) PRIMARY KEY, DOSSIER_ID VARCHAR(36), FILENAME VARCHAR(255),
    FILE_TYPE VARCHAR(50), TARGET_NAME VARCHAR, TARGET_IDENTIFIER VARCHAR,
    UPLOADED_BY VARCHAR, UPLOADED_AT TIMESTAMP_NTZ, ROW_COUNT NUMBER
);

-- RAW TABLES (MT20, MT24, HREF...)
-- (Je reprends vos définitions exactes ici en version condensée pour la lisibilité,
-- mais exécutez bien vos CREATE TABLE complets précédents pour RAW_MT20, RAW_MT24, etc.)
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_MT20 (DOSSIER_ID VARCHAR, SOURCE_FILENAME VARCHAR, "TYPE" VARCHAR, "DATE" VARCHAR, "CIBLE" VARCHAR, "X" VARCHAR, "Y" VARCHAR, "IMSI" VARCHAR, "IMEI" VARCHAR, "DUREE" VARCHAR, "DIRECTION" VARCHAR, "CORRESPONDANT" VARCHAR, "TYPE CORRESPONDANT" VARCHAR, "COMP." VARCHAR, "EFFICACITE" VARCHAR, "CELLID" VARCHAR, "ADRESSE IP VO WIFI" VARCHAR, "PORT SOURCE VO WIFI" VARCHAR, "ADRESSE2" VARCHAR, "ADRESSE3" VARCHAR, "ADRESSE4" VARCHAR, "ADRESSE5" VARCHAR, "CODE POSTAL" VARCHAR, "VILLE" VARCHAR, "PAYS" VARCHAR, "TYPE-COORD" VARCHAR);
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_MT24 (DOSSIER_ID VARCHAR, SOURCE_FILENAME VARCHAR, "TYPE" VARCHAR, "DATE" VARCHAR, "CIBLE" VARCHAR, "X" VARCHAR, "Y" VARCHAR, "IMSI" VARCHAR, "IMEI" VARCHAR, "DUREE" VARCHAR, "DIRECTION" VARCHAR, "CORRESPONDANT" VARCHAR, "TYPE CORRESPONDANT" VARCHAR, "COMP." VARCHAR, "EFFICACITE" VARCHAR, "CELLID" VARCHAR, "ADRESSE IP VO WIFI" VARCHAR, "PORT SOURCE VO WIFI" VARCHAR, "ADRESSE2" VARCHAR, "ADRESSE3" VARCHAR, "ADRESSE4" VARCHAR, "ADRESSE5" VARCHAR, "CODE POSTAL" VARCHAR, "VILLE" VARCHAR, "PAYS" VARCHAR, "TYPE-COORD" VARCHAR);
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_ANNUAIRE (DOSSIER_ID VARCHAR, SOURCE_FILENAME VARCHAR, "_ficheNumero" VARCHAR, "_ficheIMSI" VARCHAR, "_ficheIMEIvendu" VARCHAR, "_personneNom" VARCHAR, "_personnePrenom" VARCHAR, "_personneAdresse" VARCHAR, "_personneCodePostal" VARCHAR, "_personneVille" VARCHAR, "_ficheOperateur" VARCHAR, "_personneRaisonSociale" VARCHAR, "_personneSurnom" VARCHAR, "_personnePays" VARCHAR, "_representantLegalNom" VARCHAR, "_representantLegalPrenom" VARCHAR, "_representantLegalAdresse" VARCHAR, "_representantLegalCodePostal" VARCHAR, "_representantLegalVille" VARCHAR, "_ficheSIM" VARCHAR, "_ficheTypeContrat" VARCHAR, "_ficheDebutAbonnement" VARCHAR, "_ficheFinAbonnement" VARCHAR);
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_HREF_EVENTS_ORANGE (DOSSIER_ID VARCHAR, SOURCE_FILENAME VARCHAR, INPUT_ZONE_NUM VARCHAR, INPUT_ZONE_NAME VARCHAR, "Horodatage_debut" VARCHAR, "Cellule" VARCHAR, "IMSI" VARCHAR, "IMEI" VARCHAR, "MSISDN" VARCHAR, "Technologie" VARCHAR, "TypeCDR" VARCHAR, "SousTypeCDR" VARCHAR, LOADED_AT TIMESTAMP_NTZ);
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_HREF_CELLS_ORANGE (DOSSIER_ID VARCHAR, SOURCE_FILENAME VARCHAR, INPUT_ZONE_NUM VARCHAR, "CellID" VARCHAR, "CellID2" VARCHAR, "Nom" VARCHAR, "Adresse" VARCHAR, "CP" VARCHAR, "Ville" VARCHAR, "Azimut" VARCHAR, "X Lambert" VARCHAR, "Y Lambert" VARCHAR);
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_HREF_SFR (DOSSIER_ID VARCHAR, SOURCE_FILENAME VARCHAR, INPUT_ZONE_NUM VARCHAR, INPUT_ZONE_NAME VARCHAR, "Heure Eve. Reseau (heure de Paris)" VARCHAR, "Eve. Reseau" VARCHAR, "IMSI" VARCHAR, "IMEI" VARCHAR, "MSISDN" VARCHAR, "GCI" VARCHAR, "Coordonnées GPS du barycentre de la couverture de la cellule" VARCHAR, "Adresse postale implantation du Site" VARCHAR, "Code Postal implantation du Site" VARCHAR, "Ville implantation du Site" VARCHAR, "Marque Actuelle" VARCHAR, "Modèle Actuel" VARCHAR);
CREATE TABLE IF NOT EXISTS RAW_DATA.PNIJ_SRC.RAW_HREF_BOUYGUES (DOSSIER_ID VARCHAR, SOURCE_FILENAME VARCHAR, INPUT_ZONE_NUM VARCHAR, INPUT_ZONE_NAME VARCHAR, "Event.StartTime" VARCHAR, "Event.IMSI" VARCHAR, "Event.IMEI" VARCHAR, "Event.MSISDN" VARCHAR, "Cell.W84X" VARCHAR, "Cell.W84Y" VARCHAR, "Adresse1.Numero" VARCHAR, "Adresse2.Voie-Lieu" VARCHAR, "Adresse3.CodePostal" VARCHAR, "Adresse4.Ville" VARCHAR, "Cell.Techno" VARCHAR, "Event.Code" VARCHAR, "Event.Libl_Fr" VARCHAR, "Mobile.Type" VARCHAR);

-- ===========================================================================
-- 4. CRÉATION DE L'UDF (FONCTION PYTHON) - CRUCIAL
-- ===========================================================================
USE DATABASE UTILS_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE FUNCTION UDF_LAMBERT2_TO_GPS(X FLOAT, Y FLOAT)
RETURNS OBJECT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.9'
HANDLER = 'convert_lambert_to_wgs84'
AS
$$
import math
def convert_lambert_to_wgs84(x, y):
    if x is None or y is None: return None
    n = 0.7289686274; c = 11745793.39; xs = 600000.0; ys = 8199695.768
    try:
        dx = x - xs; dy = y - ys; r = math.sqrt(dx**2 + dy**2); gamma = math.atan2(dx, -dy)
        lat_iso = -1/n * math.log(abs(r/c)); lon = math.degrees(gamma/n) + 2.33722917
        phi = 2 * math.atan(math.exp(lat_iso)) - math.pi/2
        for _ in range(10):
            phi = 2 * math.atan(((1 + 0.08248325676 * math.sin(phi)) / (1 - 0.08248325676 * math.sin(phi)))**(0.08248325676/2) * math.exp(lat_iso)) - math.pi/2
        return {"lat": math.degrees(phi), "lon": lon}
    except: return None
$$;

-- ===========================================================================
-- 5. MISE À JOUR DES PRIVILÈGES (GRANT)
-- ===========================================================================
USE ROLE SECURITYADMIN; -- Ou ACCOUNTADMIN

-- --- A. Droits STREAMLIT (Lecture/Ecriture Appli) ---
GRANT USAGE ON WAREHOUSE STREAMLIT_WH TO ROLE STREAMLIT_ROLE;
-- Bases Données
GRANT USAGE ON DATABASE AUTH_DB TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON DATABASE DOSSIERS_DB TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON DATABASE RAW_DATA TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON DATABASE MARTS TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON DATABASE UTILS_DB TO ROLE STREAMLIT_ROLE; -- Utile si Streamlit veut appeler l'UDF en direct

-- Schémas
GRANT USAGE ON SCHEMA AUTH_DB.PROD TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA DOSSIERS_DB.PROD TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA RAW_DATA.PNIJ_SRC TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA MARTS.PROD TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA UTILS_DB.PUBLIC TO ROLE STREAMLIT_ROLE;

-- Tables & Fonctions
GRANT SELECT, INSERT ON TABLE AUTH_DB.PROD.USERS TO ROLE STREAMLIT_ROLE;
GRANT SELECT, INSERT, DELETE ON TABLE DOSSIERS_DB.PROD.DOSSIERS TO ROLE STREAMLIT_ROLE;
GRANT SELECT, INSERT, DELETE ON TABLE DOSSIERS_DB.PROD.FILES_LOG TO ROLE STREAMLIT_ROLE;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA RAW_DATA.PNIJ_SRC TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DATA.PNIJ_SRC TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS.PROD TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA MARTS.PROD TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON FUNCTION UTILS_DB.PUBLIC.UDF_LAMBERT2_TO_GPS(FLOAT, FLOAT) TO ROLE STREAMLIT_ROLE;

-- --- B. Droits DBT (Transformation) ---
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;

-- Lecture Sources
GRANT USAGE ON DATABASE RAW_DATA TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA RAW_DATA.PNIJ_SRC TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_DATA.PNIJ_SRC TO ROLE DBT_ROLE;

-- Lecture/Ecriture Staging & Intermediate
GRANT USAGE ON DATABASE STAGING TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STAGING.DBT_STAGING TO ROLE DBT_ROLE;
-- >>> IMPORTANT : Accès au nouveau schéma Intermediate
GRANT ALL PRIVILEGES ON SCHEMA STAGING.INTERMEDIATE TO ROLE DBT_ROLE;

-- Lecture/Ecriture Marts
GRANT USAGE ON DATABASE MARTS TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA MARTS.PROD TO ROLE DBT_ROLE;

-- >>> IMPORTANT : Droit d'utiliser l'UDF pour les calculs GPS <<<
GRANT USAGE ON DATABASE UTILS_DB TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA UTILS_DB.PUBLIC TO ROLE DBT_ROLE;
GRANT USAGE ON FUNCTION UTILS_DB.PUBLIC.UDF_LAMBERT2_TO_GPS(FLOAT, FLOAT) TO ROLE DBT_ROLE;