name: 'telephony_insights'
version: '1.0.0'
config-version: 2

profile: 'snowflake_dbt_telephony_insights_raw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# CONFIGURATION DES SCHÉMAS CIBLES
models:
  telephony_insights:
    # Configuration pour la couche STAGING
    staging:
      +database: STAGING        # Force l'écriture dans la DB STAGING
      +schema: DBT_STAGING      # Force le schéma
      +materialized: view       # Les stagings sont souvent des vues (plus rapide)
      pnij:
        # 1. Groupe COMMUNICATIONS (MT20 / MT24)
        stg_mt_orange:
          +tags: ["communications"]
        stg_mt_sfr:
          +tags: ["communications"]
        stg_mt_bouygues:
          +tags: ["communications"]
        stg_mt_free:
          +tags: ["communications"]

        # 2. Groupe RÉSEAU (HREF)
        stg_href_orange:
          +tags: ["reseau"]
        stg_href_sfr:
          +tags: ["reseau"]
        stg_href_bouygues:
          +tags: ["reseau"]

        # 3. Groupe ANNUAIRE
        stg_annuaire:
          +tags: ["annuaire"]

    intermediate:
      +database: STAGING   # Force l'écriture dans la DB INTERMEDIATE
      +schema: INTERMEDIATE # Force le schéma
      +materialized: table      # Les intermédiaires sont des tables (pour les transformations)

    # Configuration pour la couche MARTS
    marts:
      +database: MARTS          # Force l'écriture dans la DB MARTS
      +schema: PROD             # Force le schéma
      +materialized: table      # Les tables finales sont des tables (pour la perf Streamlit)

